### ISSUE TITLE
Getting `Error: Unknown error acquiring position`

### ISSUE THREAD

**Issue by yezyilomo** [ritabradley/seasons#5]
![error](https://user-images.githubusercontent.com/20328561/73714281-758eb100-4721-11ea-817e-ae559464d49e.png)

**Comment by ritabradley** [comment]
@yezyilomo  Did you allow your browser to know your location?

**Comment by yezyilomo** [comment]
I did
![bug](https://user-images.githubusercontent.com/20328561/74123440-ddd90900-4bdf-11ea-9b07-b53a82966c07.png)

**Comment by yezyilomo** [comment]
Seems like it doesn't work on firefox, I've tested it on chrome it works.

**Comment by ritabradley** [comment]
It's because it uses Chrome's location API. I'll make a version some day that's universal. Great catch though!
